[package]
name = "unladen_swallow"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "unladen_swallow"
crate-type = ["cdylib"]

[dependencies]
graph = { version = "0.2", path = "../algos" }
log = "0.4.14"
numpy = "0.16.0"
pyo3-log = "0.6.0"

[dependencies.pyo3]
version = "0.16.0"
features = ["extension-module", "macros", "pyproto", "auto-initialize"]
default-features = false
